name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: macos-latest

    env:
      HOMEBREW_NO_AUTO_UPDATE: 1
      HOMEBREW_NO_INSTALL_CLEANUP: 1
      CCACHE_DIR: ~/.ccache

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Homebrew downloads
        uses: actions/cache@v4
        with:
          path: |
            ~/Library/Caches/Homebrew
          key: ${{ runner.os }}-brew-${{ hashFiles('Brewfile') }}
          restore-keys: |
            ${{ runner.os }}-brew-

      - name: Cache ccache
        uses: actions/cache@v4
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-ccache-${{ hashFiles('CMakeLists.txt', 'cmake/**/*.cmake') }}
          restore-keys: |
            ${{ runner.os }}-ccache-

      - name: Set up Homebrew dependencies
        run: |
          brew bundle --file=Brewfile --no-upgrade

      - name: Configure environment for Qt
        run: |
          echo "QT_ROOT=$(brew --prefix qt)" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=$(brew --prefix qt)/lib/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV

      - name: Build
        run: |
          export CMAKE_C_COMPILER_LAUNCHER=ccache
          export CMAKE_CXX_COMPILER_LAUNCHER=ccache
          make build

      - name: Run CTest
        working-directory: build/generated/cmake
        run: |
          ctest --output-on-failure
